name: Build macOS binary

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          override: true
      - name: Build release binary
        run: cargo build --release --target x86_64-apple-darwin
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: n8n-workflow-sync-macos
          path: target/x86_64-apple-darwin/release/n8n-workflow-sync

